# Generated by Django 4.2.3 on 2023-07-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='htmls',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(null=True)),
                ('admin_user', models.TextField(null=True)),
                ('meta', models.TextField(null=True)),
                ('edit_access', models.TextField(null=True)),
                ('view_access', models.TextField(null=True)),
            ],
        ),
    ]
