# Generated by Django 4.2.3 on 2023-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmls',
            name='content_html',
            field=models.TextField(null=True),
        ),
    ]
