# Generated by Django 4.2.3 on 2023-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_htmls_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmls',
            name='content_css',
            field=models.TextField(null=True),
        ),
    ]
