# Generated by Django 4.2.3 on 2023-07-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_sheets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheets',
            name='content_css',
        ),
    ]
