# Generated by Django 4.2.3 on 2023-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_remove_sheets_content_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmls',
            name='view_any',
            field=models.TextField(default='no'),
        ),
    ]
